['wrench'] = {
    label = 'Wrench',
    weight = 1000,
    stack = false,
    close = true,
    consume = 0.1,
    description = 'A versatile tool used for gripping and turning objects, especially nuts and bolts.',
},
['socket_set'] = {
    label = 'Socket Set',
    weight = 1000,
    stack = false,
    close = true,
    consume = 0.1,
    description = 'A set of sockets used with a wrench for various mechanical tasks.',
},
['oil'] = {
    label = 'Engine Oil',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Lubricating oil used in engines to reduce friction and wear.',
},
['oil_filter'] = {
    label = 'Oil Filter',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'A filter that removes contaminants from engine oil.',
},
['trans_oil'] = {
    label = 'Transmission Oil',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Lubricating oil used in the transmission system.',
},
['oem_coilovers'] = {
    label = 'OEM Coilovers',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Original Equipment Manufacturer (OEM) coilover suspension units.',
},


['sport_coilovers'] = {
    label = 'Sport Coilovers',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Performance-oriented coilover suspension units for sporty driving.',
},
['race_coilovers'] = {
    label = 'Race Coilovers',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'High-performance coilover suspension units designed for racing.',
},
['shiftkit_1'] = {
    label = 'Shift Kit 1',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Basic shift kit to improve gear shifting performance.',
},
['shiftkit_2'] = {
    label = 'Shift Kit 2',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Advanced shift kit for enhanced gear shifting performance.',
},
['camshaft_1'] = {
    label = 'Camshaft 1',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Basic camshaft to improve engine performance.',
},
['camshaft_2'] = {
    label = 'Camshaft 2',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Advanced camshaft for increased engine performance.',
},
['rocker_1'] = {
    label = 'Rocker 1',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Baisc rocker arm for improved valve operation.',
},
['rocker_2'] = {
    label = 'Rocker 2',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'High-performance rocker arm for improved valve operation.',
},
['lifter_1'] = {
    label = 'Lifter 1',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Standard lifter for smooth engine operation.',
},
['lifter_2'] = {
    label = 'Lifter 2',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'High-performance lifter for enhanced engine operation.',
},
['intercooler'] = {
    label = 'Intercooler',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Device used to cool air compressed by the turbocharger.',
},
['intercooler_piping'] = {
    label = 'Intercooler Piping',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Piping system used to route air to and from the intercooler.',
},
['turbocharger'] = {
    label = 'Turbocharger',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Device used to increase engine power by forcing extra air into the combustion chamber.',
},
['bov'] = {
    label = 'Blow-off Valve',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Valve that releases excess pressure from the turbocharger system.',
},
['oilbung'] = {
    label = 'Oil Pan Bung',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Used to add an oil feed to a turbocharger.',
},
['tint_stock'] = {
    label = '0% Window Tint',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Standard clear window tint with no shading.',
},
['tint_limo'] = {
    label = '5-10% Window Tint',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Very dark window tint for maximum privacy and sun protection.',
},
['tint_lightsmoke'] = {
    label = '20-30% Window Tint',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Light smoke tint for moderate privacy and sun protection.',
},
['tint_darksmoke'] = {
    label = '40-50% Window Tint',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Dark smoke tint for significant privacy and sun protection.',
},
['tint_pureblack'] = {
    label = '90-100% Window Tint',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Pure black tint for total privacy and maximum sun protection.',
},
['heat_gun'] = {
    label = 'Heat Gun',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Tool used mainly to shrink vinyl tint.',
},
['squeegee'] = {
    label = 'Squeegee',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Tool used to push air bubbles out from under vinyl tint.',
},
['oem_rotors'] = {
    label = 'OEM Rotors',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Original Equipment Manufacturer (OEM) brake rotors for standard braking performance.',
},
['oem_brakepads'] = {
    label = 'OEM Brake Pads',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Original Equipment Manufacturer (OEM) brake pads for standard braking performance.',
},
['premium_rotors'] = {
    label = 'Premium Rotors',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'High-quality brake rotors for enhanced braking performance.',
},
['premium_brakepads'] = {
    label = 'Premium Brake Pads',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'High-quality brake pads for enhanced braking performance.',
},
['sport_rotors'] = {
    label = 'Sport Rotors',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Performance brake rotors for sporty driving.',
},
['sport_brakepads'] = {
    label = 'Sport Brakepads',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Sport brakepads for sporty braking.',
},
['race_rotors'] = {
    label = 'Race Rotors',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'High-performance brake rotors designed for racing.',
},
['race_brakepads'] = {
    label = 'Race Brake Pads',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'High-performance brake pads designed for racing.',
},
['brake_fluid'] = {
    label = 'DOT4 Brake Fluid',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'High-quality DOT4 brake fluid for effective braking performance.',
},
['vehicle_door'] = {
    label = 'Stock Univeral Vehicle Door',
    weight = 1000,
    stack = false,
    close = true,
    consume = 1,
    description = 'Used to replace doors on a vehicle.',
},